// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FinalWebTech {
	
	
	public partial class Default {
		
		protected System.Web.UI.WebControls.TextBox tbluname;
		
		protected System.Web.UI.WebControls.TextBox tblpassword;
		
		protected System.Web.UI.WebControls.Button btnLoginUser;
		
		protected System.Web.UI.WebControls.TextBox tbFullName;
		
		protected System.Web.UI.WebControls.TextBox tbUsername;
		
		protected System.Web.UI.WebControls.TextBox tbPassword;
		
		protected System.Web.UI.WebControls.TextBox tbEmail;
		
		protected System.Web.UI.WebControls.Button btnAddUserReg;
	}
}
