// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FinalWebTech {
	
	
	public partial class MarksViewer {
		
		protected System.Web.UI.WebControls.Content head;
		
		protected System.Web.UI.WebControls.Content link;
		
		protected System.Web.UI.WebControls.Content body;
		
		protected System.Web.UI.WebControls.Button tpStd;
		
		protected System.Web.UI.WebControls.Button logoutButton;
		
		protected System.Web.UI.WebControls.GridView GridView3;
		
		protected System.Web.UI.WebControls.Label RollNo;
		
		protected System.Web.UI.WebControls.Label FirstName;
		
		protected System.Web.UI.WebControls.Label LastName;
		
		protected System.Web.UI.WebControls.LinkButton lnkEdit;
		
		protected System.Web.UI.WebControls.LinkButton lnkDelete;
		
		protected System.Web.UI.WebControls.LinkButton lnkUpdate;
		
		protected System.Web.UI.WebControls.LinkButton LnkCancel;
		
		protected System.Web.UI.WebControls.ObjectDataSource MarksDataSource;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl headerStu;
		
		protected System.Web.UI.WebControls.Table tblSample;
		
		protected System.Web.UI.WebControls.Content script;
	}
}
